### ISSUE TITLE
Elsa freeze nefunguje

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#47]
https://travis-ci.org/pyvec/naucse.python.cz/builds/204727745

<details>

```
Generating HTML...
[2017-02-23 20:18:35,876] ERROR in app: Exception on /lessons/beginners/install/static/windows_32v64-bit.png [GET]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/travis/build/pyvec/naucse.python.cz/naucse/routes.py", line 61, in lesson_static
    return send_from_directory(directory, filename)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/helpers.py", line 663, in send_from_directory
    filename = safe_join(directory, filename)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/helpers.py", line 632, in safe_join
    directory = os.path.join(directory, filename)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
Traceback (most recent call last):
  File "/opt/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/pyvec/naucse.python.cz/naucse/__main__.py", line 3, in <module>
    main()
  File "/home/travis/build/pyvec/naucse.python.cz/naucse/__init__.py", line 13, in main
    cli(app, base_url='http://naucse.python.cz')
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/elsa/_cli.py", line 127, in cli
    return command()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/elsa/_cli.py", line 91, in freeze
    freeze_app(app, freezer, path, base_url)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/elsa/_cli.py", line 39, in freeze_app
    freezer.freeze()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask_frozen/__init__.py", line 286, in _build_one
    % (response.status, url))
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /lessons/beginners/install/static/windows_32v64-bit.png
```

</details>

**Comment by encukou** [comment]
Thanks.
